YallaNakol.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using YallaNakol.Data.Models;
using YallaNakol.Data.Services;
using YallaNakol.Data.ViewModel;
using YallaNakol.UI.Models;

namespace YallaNakol.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IRestaurant _restaurant;
        private readonly ICategory _category;

        public HomeController(ILogger<HomeController> logger,IRestaurant restaurant,ICategory category)
        {
            _logger = logger;
            this._restaurant = restaurant;
            this._category = category;
        }

        public IActionResult Index()
        {
            
            var homeViewModel = new HomeViewModel
            {
                Restaurants = _restaurant.AllRestaurants,
                Category=_category.AllCategories
                
            };

            return View(homeViewModel);
        }
        public IActionResult About()
        {
            return View();
        }
        [Authorize(Roles = UserRoles.Admin)]
        public IActionResult AdminPanel()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> Error([FromServices]UserManager<ApplicationUser> userManager)
        {
            //_logger.LogError();
            var user = await userManager.GetUserAsync(this.User);
            var exeptionHandlerFeature=HttpContext.Features.Get<IExceptionHandlerPathFeature>();
            _logger.LogError($"UserID:{user?.Id??"NA"}|User Mail:{user?.Email??"NA"} | " +
                             $"ErrorPath:{exeptionHandlerFeature.Path} | Exeption:{exeptionHandlerFeature.Error.Message}");
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

YallaNakol.UI/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using YallaNakol.Data.Models;
using YallaNakol.Data.Services;

namespace YallaNakol.UI.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class MenusController : Controller
    {
        private readonly IMenu _repo;

        public MenusController(IMenu context)
        {
            _repo = context;
        }

        // GET: Menus
        public IActionResult Index()
        {
            return View(_repo.AllMenus);
        }

        public IActionResult Create()
        {
            _repo.AddMenu(new Menu());
            _repo.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: Menus/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = _repo.GetMenuById(id);
                
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // POST: Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public  IActionResult DeleteConfirmed(int id)
        {
            var menu = _repo.GetMenuById(id);

            _repo.DeleteMenu(menu);
            _repo.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

    
    }
}

YallaNakol.UI/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using YallaNakol.Data.Models;
using YallaNakol.Data.Services;
using YallaNakol.Data.ViewModel;

namespace YallaNakol.UI.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class RestaurantsController : Controller
    {
        private readonly IRestaurant _restRepo; 
        private readonly IDish _dishRepo;
        private readonly ICategory _catRepo;
        private readonly IMenu _menuRepo;

        public RestaurantsController(IRestaurant context,IDish dish, ICategory cat, IMenu menu)
        {
            this._restRepo = context;
            this._dishRepo = dish;
            this._catRepo = cat;
            this._menuRepo = menu;
        }
        
        public IActionResult Index()
        {
            //string y = null;
            //var x = y.Length;
            return View(_restRepo.AllRestaurants);
        }
        [AllowAnonymous]
        // GET: Restaurants/Details/5
        public IActionResult CustomerDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var restaurant = _restRepo.GetRestaurantById(id);
            if (restaurant == null)
            {
                return NotFound();
            }

            var restaurantMenu = new RestaurantMenu
            {
                Dishes = _dishRepo.AllDishes.Where(m => m.MenuId == restaurant.MenuId),
                //Category = cat.AllCategories,
                Category = restaurant.Categories,
                Restaurant = restaurant
            };
            TempData["Reffer"] = Request.Headers["Referer"].ToString();
            return View(restaurantMenu);
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var restaurant = _restRepo.GetRestaurantById(id);
            if (restaurant == null)
            {
                return NotFound();
            }

          
            return View(restaurant);
        }
        // GET: Restaurants/Create
        public IActionResult Create()
        {
            ViewData["MenuId"] = new SelectList(_menuRepo.AllMenus, "Id", "Id");

            return View();
        }

        // POST: Restaurants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                _restRepo.AddRestaurant(restaurant);
                _restRepo.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MenuId"] = new SelectList(_menuRepo.AllMenus, "Id", "Id");

            return View(restaurant);
        }
        
        // GET: Restaurants/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            //ViewBag.MenuId = new SelectList()

            var restaurant = _restRepo.GetRestaurantById(id);

            if (restaurant == null)
            {
                return NotFound();
            }
            ViewData["MenuId"] = new SelectList(_menuRepo.AllMenus, "Id", "Id", restaurant.MenuId);

            return View(restaurant);
        }
        
        // POST: Restaurants/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name,Address,Description,Rate,ImageUrl,PhoneNumber,WorkingHours,DeliveryAreas,MenuId")] Restaurant restaurant)
        {
            if (id != restaurant.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _restRepo.UpdateRestaurant(restaurant);
                    _restRepo.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_restRepo.RestaurantExists(restaurant.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MenuId"] = new SelectList(_menuRepo.AllMenus, "Id", "Id");

            return View(restaurant);
        }
        
        // GET: Restaurants/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurant = _restRepo.GetRestaurantById(id);
            if (restaurant == null)
            {
                return NotFound();
            }

            return View(restaurant);
        }

        // POST: Restaurants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var restaurant = _restRepo.GetRestaurantById(id);
             _restRepo.DeleteRestaurant(restaurant);
            _restRepo.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

YallaNakol.UI/Views/Home/About.cshtml
<div id="about">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-6 ">
                <div class="about-img"><img src="~/img/about.jpg" class="img-responsive" alt=""></div>
            </div>
            <div class="col-xs-12 col-md-6">
                <div class="about-text">
                    <h2 style="font-family:'Dancing Script', cursive">WHAT IS Yalla Nakol</h2>
                    <hr>
                    <p>Millions of people around the world ask the same question everyday “What will I eat today?” It’s the question that triggered the journey to build Yalla Nakol
                     Yalla Nakol is an Egypt based company that started in 2021 with the vision to help people decide what to eat.
                    We are building a platform that combines a social, visual and personalized experience to help people discover and order the food they love.</p>
                </div>
            </div>
        </div>
    </div>
</div>

YallaNakol.UI/Views/Home/AdminPanel.cshtml
@model IEnumerable<YallaNakol.Data.Models.Restaurant>

@{
    ViewData["Title"] = "AdminPanel";
}

<h2>Admin Panel</h2>

<table class="table">
    <thead>
        <tr>
            <td>
                <a class="btn btn-warning" asp-controller="Restaurants" asp-action="Index">Manage Restaurants</a>
            </td>
        </tr>
        <tr>
            <td>
                <a class="btn btn-warning" asp-controller="Menus" asp-action="Index">Manage Menus</a>

            </td>
        </tr>
    </thead>
</table>

YallaNakol.UI/Views/Home/Index.cshtml
@model HomeViewModel
@{int FlagCount = 0; }
@section header {
    <header id="header">
        <div class="intro">
            <div class="overlay">
                <div class="container">
                    <div class="row">
                        <div class="intro-text">
                            <h1>Yalla Nakol</h1>
                            <p>High Quality Restraunts </p>
                            <a href="#about" class="btn btn-custom btn-lg page-scroll">Discover Story</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div style="height:30px">

        </div>
    </header>
}
@section filter {
    <div class="row">
        <div class="categories">
            <ul class="cat">
                <li>
                    <ol class="type">
                        <li><a href="#" data-filter=".everyClass">All</a></li>
                        @foreach (var item in Model.Category)
                        {
                            <li><a href="#" data-filter=".@item.Name">@item.Name</a></li>
                        }
                    </ol>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
    </div>
}
<div class="row">
    <div class="portfolio-items">
        @foreach (var item in Model.Restaurants)
        {
            <partial name="PartialViews/_Restaurant" model="item" />
        }
    </div>
</div>