YallaNakol.UI/Controllers/DishesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using YallaNakol.Data.Models;
using YallaNakol.Data.Services;

namespace YallaNakol.UI.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class DishesController : Controller
    {
        private readonly IDish _dishRepo;
        private readonly IRestaurant _restRepo;
        private readonly ICategory _catRepo;
        private readonly IMenu _menuRepo;

        public DishesController(IDish dish, IRestaurant rest, ICategory cat, IMenu menu)
        {
            _dishRepo = dish;
            this._restRepo = rest;
            this._catRepo = cat;
            this._menuRepo = menu;
        }
     
        public IActionResult Index(int? id)
        {
            TempData["RestID"] = id;
            return View(_dishRepo.AllDishes.Where(D=>D.MenuId == _restRepo.GetRestaurantById(id).MenuId).ToList());
        }

        // GET: Dishes/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var dish = _dishRepo.GetDishById(id);
            if (dish == null)
            {
                return NotFound();
            }
            ViewBag.RestID = TempData["RestID"];
            TempData.Keep("RestID");
            return View(dish);
        }

        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_catRepo.AllCategories, "Id", "Name");
            ViewData["MenuId"] = new SelectList(_menuRepo.AllMenus, "Id", "Id");
            ViewBag.RestID = TempData["RestID"];
            TempData.Keep("RestID");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Dish dish)
        {
            if (ModelState.IsValid)
            {
                _dishRepo.AddDish(dish);
                _dishRepo.SaveChanges();
                return RedirectToAction(nameof(Index), new { id = TempData["RestID"] });
            }
            ViewData["CategoryId"] = new SelectList(_catRepo.AllCategories, "Id", "Name");
            ViewData["MenuId"] = new SelectList(_menuRepo.AllMenus, "Id", "Id");
            ViewBag.RestID = TempData["RestID"];
            return View(dish);
        }

        // GET: Dishes/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dish = _dishRepo.GetDishById(id);
            if (dish == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_catRepo.AllCategories, "Id", "Name",dish.CategoryId);
            ViewData["MenuId"] = new SelectList(_menuRepo.AllMenus, "Id", "Id",dish.MenuId);
            ViewBag.RestID = TempData["RestID"];
            TempData.Keep("RestID");
            return View(dish);
        }

        // POST: Dishes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Dish dish)
        {
            if (id != dish.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _dishRepo.UpdateDish(dish);
                    _dishRepo.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_dishRepo.DishExists(dish.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { id = TempData["RestID"] });
            }
            ViewData["CategoryId"] = new SelectList(_catRepo.AllCategories, "Id", "Name",dish.CategoryId);
            ViewData["MenuId"] = new SelectList(_menuRepo.AllMenus, "Id", "Id",dish.MenuId);
            ViewBag.RestID = TempData["RestID"];
            TempData.Keep("RestID");
            return View(dish);
        }

        // GET: Dishes/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dish = _dishRepo.GetDishById(id);
            if (dish == null)
            {
                return NotFound();
            }
            ViewBag.RestID = TempData["RestID"];
            TempData.Keep("RestID");
            return View(dish);
        }

        // POST: Dishes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var dish = _dishRepo.GetDishById(id);
            _dishRepo.DeleteDish(dish);
            _dishRepo.SaveChanges();
            return RedirectToAction(nameof(Index),new { id = TempData["RestID"] });
        }
    }
}

YallaNakol.UI/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using YallaNakol.Data.Models;
using YallaNakol.Data.Services;
using YallaNakol.Data.ViewModel;

namespace YallaNakol.UI.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class RestaurantsController : Controller
    {
        private readonly IRestaurant _restRepo; 
        private readonly IDish _dishRepo;
        private readonly ICategory _catRepo;
        private readonly IMenu _menuRepo;

        public RestaurantsController(IRestaurant context,IDish dish, ICategory cat, IMenu menu)
        {
            this._restRepo = context;
            this._dishRepo = dish;
            this._catRepo = cat;
            this._menuRepo = menu;
        }
        
        public IActionResult Index()
        {
            //string y = null;
            //var x = y.Length;
            return View(_restRepo.AllRestaurants);
        }
        [AllowAnonymous]
        // GET: Restaurants/Details/5
        public IActionResult CustomerDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var restaurant = _restRepo.GetRestaurantById(id);
            if (restaurant == null)
            {
                return NotFound();
            }

            var restaurantMenu = new RestaurantMenu
            {
                Dishes = _dishRepo.AllDishes.Where(m => m.MenuId == restaurant.MenuId),
                //Category = cat.AllCategories,
                Category = restaurant.Categories,
                Restaurant = restaurant
            };
            TempData["Reffer"] = Request.Headers["Referer"].ToString();
            return View(restaurantMenu);
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var restaurant = _restRepo.GetRestaurantById(id);
            if (restaurant == null)
            {
                return NotFound();
            }

          
            return View(restaurant);
        }
        // GET: Restaurants/Create
        public IActionResult Create()
        {
            ViewData["MenuId"] = new SelectList(_menuRepo.AllMenus, "Id", "Id");

            return View();
        }

        // POST: Restaurants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                _restRepo.AddRestaurant(restaurant);
                _restRepo.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MenuId"] = new SelectList(_menuRepo.AllMenus, "Id", "Id");

            return View(restaurant);
        }
        
        // GET: Restaurants/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            //ViewBag.MenuId = new SelectList()

            var restaurant = _restRepo.GetRestaurantById(id);

            if (restaurant == null)
            {
                return NotFound();
            }
            ViewData["MenuId"] = new SelectList(_menuRepo.AllMenus, "Id", "Id", restaurant.MenuId);

            return View(restaurant);
        }
        
        // POST: Restaurants/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name,Address,Description,Rate,ImageUrl,PhoneNumber,WorkingHours,DeliveryAreas,MenuId")] Restaurant restaurant)
        {
            if (id != restaurant.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _restRepo.UpdateRestaurant(restaurant);
                    _restRepo.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_restRepo.RestaurantExists(restaurant.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MenuId"] = new SelectList(_menuRepo.AllMenus, "Id", "Id");

            return View(restaurant);
        }
        
        // GET: Restaurants/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurant = _restRepo.GetRestaurantById(id);
            if (restaurant == null)
            {
                return NotFound();
            }

            return View(restaurant);
        }

        // POST: Restaurants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var restaurant = _restRepo.GetRestaurantById(id);
             _restRepo.DeleteRestaurant(restaurant);
            _restRepo.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

YallaNakol.UI/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using YallaNakol.Data.Services;

namespace YallaNakol.UI.Controllers
{
    
    public class ShoppingCartController : Controller
    {
        private readonly IShoppingCart _shoppingCart;
        private readonly IDish _dish;

        public ShoppingCartController(IShoppingCart shoppingCart,
                                      IDish dish)
        {
            this._shoppingCart = shoppingCart;
            _dish = dish;
        }
        // GET: ShoppingCartController
        public ActionResult Index()
        {
            // TEST DATA ONLY 
            // START OF TEST DATA
            /////////var addedDish1 = _dish.GetDishById(1);
           // var addedDish2 = _dish.GetDishById(2);
           // var addedDish3 = _dish.GetDishById(3);
           //
            //////////_shoppingCart.AddDish(addedDish1, 1);
           // _shoppingCart.AddDish(addedDish2, 3);
           // _shoppingCart.AddDish(addedDish3, 2);
            ////////_shoppingCart.SaveChanges();
            // END OF TEST DATA


            // Redirect To Home If Empty Cart
            if (_shoppingCart.IsEmpty)
                return LocalRedirect("/Home");


            return View(_shoppingCart);
        }

        [Route("ShoppingCart/AddToCart/dishId")]
        public ActionResult AddToCart(int dishId, int amount = 1)
        {
            var addedDish = _dish.GetDishById(dishId);
            if (addedDish != null)
            {

                _shoppingCart.AddDish(addedDish, amount);
                _shoppingCart.SaveChanges();

            }

            // get the caller URL which we will redirect to:

            Uri callingUrl = Request.GetTypedHeaders().Referer;
            return Redirect(callingUrl.OriginalString);
            //return RedirectToAction("Index");
        }

        [Route("ShoppingCart/RemoveFromCart/dishId")]
        public ActionResult RemoveFromCart(int dishId)
        {
            var removedDish = _dish.GetDishById(dishId);
            if (removedDish != null)
            {
                _shoppingCart.RemoveDish(removedDish);
                _shoppingCart.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

YallaNakol.UI/Views/Shared/PartialViews/_Restaurant.cshtml
@model Restaurant
@using System.Text
@{ 
    var RestaurantCategory = new StringBuilder();

    }

<style>
    .Restaurant-item-Display {
        /*width:100%;*/
        position: relative;
        overflow: hidden;
    }

    .newLayoutlayer {
        position: absolute;
        top: 100%;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(255,255,255,.7);
        text-align: center;
        padding: 20px;
        transition: top 0.8s ease-in-out;
    }

    .Restaurant-item-Display:hover .newLayoutlayer {
        top: 0;
    }

    .py-2 {
        padding: 8px;
    }

    .py-3 {
        padding: 12px;
    }
    .checked {
        color: orange;
    }
</style>
@for (int i = 0; i < (Model?.Categories?.Count??0); i++)
{
    RestaurantCategory.Append(Model.Categories.ElementAt(i).Name?? "All");
    if(!(i==Model.Categories.Count-1))
        RestaurantCategory.Append(" ");
}



<div class="col-md-4 col-sm-6 py-3 everyClass @RestaurantCategory.ToString()">
    <div class="Restaurant-item-Display ">
        <img src="@Model.ImageUrl" class="img-rounded" style="width:100%; height:250px;">
        <div class="newLayoutlayer">
            <h3>@Model.Name</h3>
            <a asp-action="CustomerDetails" asp-controller="Restaurants"
               asp-route-id="@Model.Id" class="btn btn-primary">Order Now</a>
        </div>
    </div>
    <div class="py-2">


        <img class="img-rounded" src="@Model.ImageUrl" style="width:30px; height:30px;" />
        <span>@RestaurantCategory.ToString().Replace(' ', '-')</span>
        <div>
            @for (int i = 0; i < 5; i++)
            {
                int.TryParse(Model.Rate, out int rating);
                if (i < rating)
                {
                    <span class="fa fa-star checked"></span>
                }
                else
                {
                    <span class="fa fa-star"></span>
                }
            }

        </div>
    
        
    </div>
    <div class="row">
        <div class="col-md-4 py-2">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-truck" viewBox="0 0 16 16">
                <path d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
            </svg>
            <span>90mins</span>
        </div>

        <div class="col-md-4 py-2">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z" />
            </svg>
            <span>Live Track</span>
        </div>

        <div class="col-md-4 py-2">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                 class="bi bi-emoji-smile" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                <path d="M4.285 9.567a.5.5 0 0 1 .683.183A3.498 3.498 0 0 0 8 11.5a3.498 3.498 0 0 0 3.032-1.75.5.5 0 1 1 .866.5A4.498 4.498 0 0 1 8 12.5a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .183-.683zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z" />
            </svg>
            <span>Reviews</span>
        </div>
    </div>
</div>

YallaNakol.UI/Views/Shared/PartialViews/_RestaurantDish.cshtml
@model Dish

<style>
    .span2 {
        width: 175px;
        float: left;
        display: block;
        line-height: 20px;
    }

        .span2 img {
            margin-top: 14px;
            border-radius: 10px;
            width: 90%;
            height: 125px;
            vertical-align: middle;
            margin-right: 5px;
        }


</style>
<hr class="soften">
<div class="@Model.Category.Name portfolio-item">

    <div class="span2">
        <img src="@Model.ImageUrl" alt="">
    </div>
    <div class="span6">
        <h5>@Model.Name</h5>
        <p>
            @Model.Description
        </p>
    </div>
    <div class="span4 alignR">
        <form class="form-horizontal qtyFrm">
            <h3> @Model.Price L.E.</h3>
            <div class="btn-group">
                <span class="icon-shopping-cart">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                        <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                    </svg>
                    <a asp-action="AddToCart" asp-controller="ShoppingCart" asp-route-dishId="@Model.Id" class="shopBtn">Add to cart</a>
                </span>

                @*<br />*@
                @*<a asp-action="Details" asp-controller="Dishes" asp-route-id="@Model.Id" class="shopBtn">View Dish</a>*@
            </div>
        </form>
    </div>
</div>