YallaNakol.UI/Component/ShoppingCartIconViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YallaNakol.Data.Models;
using YallaNakol.Data.Services;

namespace YallaNakol.UI.Component
{
    public class ShoppingCartIconViewComponent:ViewComponent
    {
        private readonly IShoppingCart _shoppingCart;

        public ShoppingCartIconViewComponent(IShoppingCart shoppingCart)
        {
            this._shoppingCart = shoppingCart;
        }

        public IViewComponentResult Invoke()
        {
            return View(_shoppingCart.ShoppingCartItems.Count());
        }
    }
}

YallaNakol.UI/Views/Shared/_ErrorLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Touché</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Favicons
        ================================================== -->
    <link rel="shortcut icon" href="~/img/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" href="~/img/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/img/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/img/apple-touch-icon-114x114.png">

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="~/fonts/font-awesome/css/font-awesome.css">

    <!-- Stylesheet
        ================================================== -->
    <link rel="stylesheet" type="text/css" href="~/css/style.css">
    <link rel="stylesheet" type="text/css" href="~/css/nivo-lightbox/nivo-lightbox.css">
    <link rel="stylesheet" type="text/css" href="~/css/nivo-lightbox/default.css">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script:400,700" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
    <!-- Navigation
        ==========================================-->
    <nav id="menu" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                <a class="navbar-brand page-scroll" href="#page-top">Yalla Nakol</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-action="Index" asp-controller="Home">Restaurants</a></li>
                    <li><a asp-action="About" asp-controller="Home">About</a></li>
                    <li><a class="page-scroll" href="#footer">Contact Us</a></li>
                    <partial name="_LoginPartial" />
                </ul>

            </div>
        </div>
    </nav>


    @RenderBody();


    <div id="call-reservation" class="text-center">
        <div class="container">
            <h2>Want to make a reservation? Call <strong>1-887-654-3210</strong></h2>
        </div>
    </div>


    <div id="footer">
        <div class="container text-center">
            <div class="col-md-4">
                <h3>Address</h3>
                <div class="contact-item">
                    <p>4321 California St,</p>
                    <p>San Francisco, CA 12345</p>
                </div>
            </div>
            <div class="col-md-4">
                <h3>Opening Hours</h3>
                <div class="contact-item">
                    <p>Mon-Thurs: 10:00 AM - 11:00 PM</p>
                    <p>Fri-Sun: 11:00 AM - 02:00 AM</p>
                </div>
            </div>
            <div class="col-md-4">
                <h3>Contact Info</h3>
                <div class="contact-item">
                    <p>Phone: +1 123 456 1234</p>
                    <p>Email: info@company.com</p>
                </div>
            </div>
        </div>
        <div class="container-fluid text-center copyrights">
            <div class="col-md-8 col-md-offset-2">
                <div class="social">
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                    </ul>
                </div>
                <p>&copy; 2016 Touché. All rights reserved. Designed by <a href="http://www.templatewire.com" rel="nofollow">TemplateWire</a></p>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="~/js/jquery.1.11.1.js"></script>
    <script type="text/javascript" src="~/js/bootstrap.js"></script>
    <script type="text/javascript" src="~/js/SmoothScroll.js"></script>
    <script type="text/javascript" src="~/js/nivo-lightbox.js"></script>
    <script type="text/javascript" src="~/js/jquery.isotope.js"></script>
    <script type="text/javascript" src="~/js/jqBootstrapValidation.js"></script>
    <script type="text/javascript" src="~/js/main.js"></script>
    @await RenderSectionAsync("Nagdy", required: false)
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

YallaNakol.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>YallaNakol</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Favicons
        ================================================== -->
    <link rel="shortcut icon" href="~/img/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" href="~/img/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/img/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/img/apple-touch-icon-114x114.png">

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="~/fonts/font-awesome/css/font-awesome.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Stylesheet
        ================================================== -->
    <link rel="stylesheet" type="text/css" href="~/css/style.css">
    <link rel="stylesheet" type="text/css" href="~/css/nivo-lightbox/nivo-lightbox.css">
    <link rel="stylesheet" type="text/css" href="~/css/nivo-lightbox/default.css">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script:400,700" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
    <!-- Navigation
        ==========================================-->
    <nav id="menu" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                <a class="navbar-brand page-scroll" asp-action="Index" asp-controller="Home">Yalla Nakol</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-action="Index" asp-controller="Home">Restaurants</a></li>
                    <li><a asp-action="About" asp-controller="Home">About</a></li>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                    <li><a asp-action="AdminPanel" asp-controller="Home">Control Panel</a></li>
                    }

                    <partial name="_LoginPartial" />
                    <li>@await Component.InvokeAsync("ShoppingCartIcon")</li>
                </ul>

            </div>

            <!-- /.navbar-collapse -->
        </div>
    </nav>
    <!-- Header -->
    @RenderSection("header", required: false)
    <!-- Restaurant Menu Section -->
    <div id="restaurant-menu">
        <div class="section-title text-center center">
            <div class="overlay">
                <h2>Restuarants</h2>
                <hr>
                <p>In Yalla Nakol All The World Is In Your Hands </p>
            </div>
        </div>
    </div>
    @RenderSection("filter", required: false)
    <div class="container">
        @RenderBody()
    </div>
    <!-- Team Section -->
    <div id="team" class="text-center">
        <div class="overlay">
            <div class="container">
                <div class="col-md-10 col-md-offset-1 section-title">
                    <h2>Meet Our Team</h2>
                    <hr>
                    <p>
                        ITI Information Technology Institute
                    </p>
                </div>
                <div id="row">
                    <div class="col-md-2 team">
                        <div class="thumbnail">
                            <!--<div class="team-img">-->@*<img src="img/team/01.jpg" alt="...">*@<!--</div>-->
                            <div class="caption">
                                <h3>Abdallah Abdelhamid</h3>
                                @*<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dapibus leo nec ornare diam.</p>*@
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 team">
                        <div class="thumbnail">
                            <!--<div class="team-img">-->@*<img src="img/team/02.jpg" alt="...">*@<!--</div>-->
                            <div class="caption">
                                <h3>Ahmed Mahmoud AbdAlAty</h3>
                                @*<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dapibus leo nec ornare diam.</p>*@
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2 team">
                        <div class="thumbnail">
                            <!--<div class="team-img">-->@*<img src="img/team/03.jpg" alt="...">*@<!--</div>-->
                            <div class="caption">
                                <h3>Ahmed Nagdy</h3>
                                @*<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dapibus leo nec ornare diam.</p>*@
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2 team">
                        <div class="thumbnail">
                            <!--<div class="team-img">-->@*<img src="img/team/03.jpg" alt="...">*@<!--</div>-->
                            <div class="caption">
                                <h3>Eslam ElNagar</h3>
                                @*<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dapibus leo nec ornare diam.</p>*@
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 team">
                        <div class="thumbnail">
                            <!--<div class="team-img">-->@*<img src="img/team/03.jpg" alt="...">*@<!--</div>-->
                            <div class="caption">
                                <h3>Mohamed Ahmed Shawky</h3>
                                @*<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dapibus leo nec ornare diam.</p>*@
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Call Reservation Section -->
    <div id="call-reservation" class="text-center">
        <div class="container">
            <h2>Want to make a reservation? send to <strong>yallaanakool@gmail.com</strong></h2>
        </div>
    </div>


    <div id="footer">
        <div class="container text-center">
            <div class="col-md-4">
                <h3>Address</h3>
                <div class="contact-item">
                    <p>28 Km by Cairo / Alexandria Desert Road, 6 October, B148, Egypt</p>
                    <p>Cairo,Egypt</p>
                </div>
            </div>
            <div class="col-md-4">
                <h3>Opening Hours</h3>
                <div class="contact-item">
                    <p>Mon-Thurs: 10:00 AM - 11:00 PM</p>
                    <p>Fri-Sun: 11:00 AM - 02:00 AM</p>
                </div>
            </div>
            <div class="col-md-4">
                <h3>Contact Info</h3>
                <div class="contact-item">
                    <p>Phone: +01007758755</p>
                    <p>
                        Email: yallaanakool@gmail.com
                    </p>
                </div>
            </div>
        </div>
        <div class="container-fluid text-center copyrights">
            <div class="col-md-8 col-md-offset-2">
                <div class="social">
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                    </ul>
                </div>
                <p>&copy; 2021 YallaaNakool. All rights reserved. Designed by <a href="http://www.templatewire.com" rel="nofollow">TemplateWire</a></p>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="~/js/jquery.1.11.1.js"></script>
    <script type="text/javascript" src="~/js/bootstrap.js"></script>
    @*<script type="text/javascript" src="~/js/SmoothScroll.js"></script>*@
    <script type="text/javascript" src="~/js/nivo-lightbox.js"></script>
    <script type="text/javascript" src="~/js/jquery.isotope.js"></script>
    <script type="text/javascript" src="~/js/jqBootstrapValidation.js"></script>

    @*<script type="text/javascript" src="~/js/contact_me.js"></script>*@
    <script type="text/javascript" src="~/js/main.js"></script>

    <script>
        window.onload = function () {
            var firstChild = document.querySelector(".type a");
            firstChild.classList.add("active")
            firstChild.click()
        }
    </script>

    @await RenderSectionAsync("Nagdy", required: false)
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>